<?php

return [
    // drug/substance instead of object
    'ABC'   => ['full_term' => 'American Broadcasting Company', 'type' => 'organisation'],
    'BBC'   => ['full_term' => 'British Broadcasting Company', 'type' => 'organisation'],
    'BLS'   => ['full_term' => '', 'type' => ''],
    'CB'    => ['full_term' => 'Citizens band radio', 'type' => 'object'],
    'CBS'   => ['full_term' => 'Columbia Broadcasting System', 'type' => 'organisation'],
    'CD'    => ['full_term' => 'Compact disc', 'type' => 'object'],
    'CEO'   => ['full_term' => 'Chief executive officer', 'type' => 'position'],
    'CIA'   => ['full_term' => 'Central Intelligence Agency', 'type' => 'organisation'],
    'CNN'   => ['full_term' => 'Cable News Network', 'type' => 'organisation'],
    'DNA'   => ['full_term' => 'Deoxyribonucleic acid', 'type' => 'object'],
    'DVD'   => ['full_term' => 'Digital video disk', 'type' => 'object'],
    'FCC'   => ['full_term' => 'Federal Communications Commission', 'type' => 'organisation'],
    'FDS'   => ['full_term' => 'Food and Drug Administration', 'type' => 'organisation'],
    'FLA'   => ['full_term' => 'Florida', 'type' => 'state'],
    'GHB'   => ['full_term' => 'Gamma-hydroxybutyrate', 'type' => 'object'],
    'ICU'   => ['full_term' => 'Intensive care unit', 'type' => 'place'],
    'IMAX'  => ['full_term' => 'Film format', 'type' => 'brand'],
    'IQ'    => ['full_term' => 'Intelligence quotient', 'type' => ''],
    'IRS'   => ['full_term' => 'Internal Revenue Service', 'type' => 'organisation'],
    'JC'    => ['full_term' => 'JC Penney', 'type' => 'brand'],
    'JFK'   => ['full_term' => 'John F. Kennedy International Airport', 'type' => 'place'],
    'HIV'   => ['full_term' => 'human immunodeficiency virus', 'type' => 'object'],
    'II'    => ['full_term' => 'two', 'type' => 'name'],
    'KLF'   => ['full_term' => '', 'type' => 'organisation'],
    'LA'    => ['full_term' => 'Los Angeles', 'type' => 'town'],
    'LCD'   => ['full_term' => 'Liquid-crystal display', 'type' => 'object'],
    'LESB'  => ['full_term' => '', 'type' => ''],
    'LSD'   => ['full_term' => 'Lysergic acid diethylamide', 'type' => 'object'],
    'LST'   => ['full_term' => 'Landing Ship, Tank', 'type' => 'object'],
    'MC'    => ['full_term' => 'Master of Ceremonies', 'type' => 'position'],
    'MCs'   => ['full_term' => 'Master of Ceremonies', 'type' => 'position'],
    'MDMA'  => ['full_term' => 'Methylenedioxymethamphetamine', 'type' => 'object'],
    'MTV'   => ['full_term' => 'Music Television', 'type' => 'organisation'],
    'NASA'  => ['full_term' => 'National Aeronautics and Space Administration', 'type' => 'organisation'],
    'NBC'   => ['full_term' => 'National Broadcasting Company', 'type' => 'organisation'],
    'NF'    => ['full_term' => '', 'type' => ''],
    'NRA'   => ['full_term' => 'National Rifle Association', 'type' => 'organisation'],
    'NWA'   => ['full_term' => 'Niggers With Attitude', 'type' => 'organisation'],
    'NYC'   => ['full_term' => 'New York City', 'type' => 'town'],
    'NYPD'  => ['full_term' => 'New York City Police Department', 'type' => 'organisation'],
    'PA'    => ['full_term' => 'Pennsylvania', 'type' => 'state'],
    'PFC'   => ['full_term' => 'Private first class', 'type' => 'position'],
    'PMS'   => ['full_term' => 'Premenstrual syndrome', 'type' => ''],
    'PR'    => ['full_term' => 'Puerto Rican', 'type' => 'country'],
    'REM'   => ['full_term' => 'REM', 'type' => 'organisation'],
    'TRL'   => ['full_term' => 'Total Request Live', 'type' => 'organisation'],
    'TV'    => ['full_term' => 'Television', 'type' => 'object'],
    'UK'    => ['full_term' => 'United Kingdom', 'type' => 'country'], // change this to other file
    'UFO'   => ['full_term' => 'Unidentified flying object', 'type' => 'object'],
    'USO'   => ['full_term' => 'United Service Organizations', 'type' => 'organisation'],
    'VCR'   => ['full_term' => 'Videocassette recorder', 'type' => 'object'],
    'VP'    => ['full_term' => 'Vice President', 'type' => 'position'],
    'VW'    => ['full_term' => 'Volkswagen', 'type' => 'brand'],
    'WLSD'  => ['full_term' => 'Wise Lee Scott Dickenson', 'type' => 'organisation'],
    'ZZ'    => ['full_term' => '', 'type' => 'organisation'],

];
