<?php

return [

    'Accattone', // movie
    'Adidas',
    'Armalite',
    'Armani',
    'Bacardi',
    'Baileys',
    'Bally',
    'Barbie',
    'Batego',
    'Beatlemania',
    'Beechams',
    'Benz',
    'Benzie',
    'Birchmount', //stadium
    'Blackstrap',
    'Blueboy', // magazine
    'Brandivino',
    'Buick',
    'Buicks',
    'Bundeburg',
    'Cadi',
    'Cadillac',
    'Cadillacs',
    'Calvin', // also a name
    'Cartier',
    'Casio',
    'Chablis', // also a place
    'Chevrolet',
    'Chevy',
    'Chrysler',
    'Coca',
    'Coke',
    'Corona',
    'Corvette',
    'Crayola',
    'Dacron',
    'Danneman',
    'Darjeeling',
    'Datsuns',
    'Dereon',
    'Dexydrine',
    'Dijon',
    'Dolce',
    'Donna', // also a name
    'Dorado',
    'Dow',
    'Doz',
    'Dupont',
    'Edsel',
    'Eldorado',
    'Falstaff', // beer
    'Fendi',
    'Fu',
    'Gabbana',
    'Gideon',
    'Glock',
    'Gucci',
    'Halston',
    'Hardiflex',
    'Harpers',
    'Henri',
    'Hilton',
    'Honda',
    'Hoover',
    'Horae',
    'Horten',
    'Indy',
    'Jaguar', // also animal
    'Jaycees',
    'Jeeps',
    'Johnstown',
    'Karan',
    'Keds',
    'Khus',
    'Klein',
    'Kohoutek',
    'Kombi',
    'Kraft',
    'Kung',
    'Lee', // jeans
    'Lego',
    'Listerine',
    'Longines',
    'Luger',
    'Lugers',
    'Mac', // also a name and a word
    'Marlboro',
    'Mastercard',
    'Maybelline',
    'Mercedes',
    'Monopoly', // also a word
    'Moschino',
    'Nescafe',
    'Nike',
    'Nyquil',
    'Pabst',
    'Panaflex',
    'Pantone',
    'Penney',
    'Pennzoil',
    'Pepsi',
    'Perignon',
    'Peyton', // Peyton Place tv show
    'Playboy',
    'Porsches',
    'Prozac',
    'Reebok',
    'Romilar', // cough syrup
    'Royce',
    'Saran', // Saran Wrap
    'Scripto',
    'Sears', // also word
    'Seconal',
    'Sharpie',
    'Smurf',
    'Solitaire',
    'Soloflex',
    'Sony',
    'Starbucks',
    'Symphonette', 
    'Tampax',
    'Teflon',
    'Tesco',
    'Texaco',
    'Titanic',
    'Tropicana',
    'Tylenol',
    'Uzi',
    'Vaseline',
    'Vaselines',
    'Vanetto',
    'Vegemite',
    'Velcro',
    'Visine',
    'Vogue',
    'Vuitton',
    'Walker', // Johnny Walker, also a "word"
    'Walkman',
    'Walmart',
    'Winterman',
    'Wonderbread',
    'Woodbines',
    'Woody',
    'Wookiee',
    'Xerox',
    'Zelda', // video game?

];
