<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Places
    |--------------------------------------------------------------------------
    |
    | Suburbs, neighbourhoods, rivers, mountains, islands, parks, hotels,
    | churches
    |
    */

    "alderaan's"    => "Alderaan's",
    'amazon'        => 'Amazon',
    'amazonians'    => 'Amazonians',
    'andalusia'     => 'Andalusia',
    'annan'         => 'Annan', // Annan Waters, river
    'antarctic'     => 'Antarctic',
    'appalachia'    => 'Appalachia',
    'appel'         => 'Appel',
    'argonauts'     => 'Argonauts',
    'atlantic'      => 'Atlantic',
    'atlantis'      => 'Atlantis',
    'avalon'        => 'Avalon',
    'babylon'       => 'Babylon',
    'bali'          => 'Bali',
    'balie'         => 'Balie',
    'baltic'        => 'Baltic',
    'bedford-stuy'  => 'Bedford-Stuy',
    'bergere'       => 'Bergere', // Folies Bergere
    'bondi'         => 'Bondi',
    'brixton'       => 'Brixton',
    'broadway'      => 'Broadway',
    'brooklyn'      => 'Brooklyn',
    "brooklyn's"    => "Brooklyn's",
    'bronx'         => 'Bronx',
    'canaan'        => 'Canaan',
    'carre'         => 'Carre', // Vieux Carre neighborhood in New Orleans
    'cavour'        => 'Cavour', // Piazza Cavour
    'challen'       => 'Challen', // UK shipping forecast area
    'chelsea'       => 'Chelsea', // also a name
    'chesapeake'    => 'Chesapeake',
    'chicano'       => 'Chicano', // Chicano City park
    'chinatown'     => 'Chinatown',
    'cicero'        => 'Cicero', // Chicago suburb, also a name
    'clapham'       => 'Clapham',
    'clubland'      => 'Clubland',
    'coeur'         => 'Coeur', // Sacre Couer
    'collingwood'   => 'Collingwood',
    'coney'         => 'Coney', // Coney Island
    'costa'         => 'Costa', //  Costa del Malvinas
    'cuyahoga'      => 'Cuyahoga',
    'disneyland'    => 'Disneyland',
    'disneyworld'   => 'Disneyworld',
    'doheny'        => 'Doheny',
    'dorado'        => 'Dorado', // El Dorado
    'eden'          => 'Eden',
    'eiffel'        => 'Eiffel', // after a name
    "elaine's"      => "Elaine's", // bar in NYC
    'euphrates'     => 'Euphrates', // river
    'euston'        => 'Euston',
    'fiddister'     => 'Fiddister',
    'fillmore'      => 'Fillmore',
    'fiscay'        => 'Fiscay',
    'fitzroy'       => 'Fitzroy',
    'folsom'        => 'Folsom',
    'forfend'       => 'Forfend',
    'forth'         => 'Forth',
    'galilee'       => 'Galilee',
    'galway'        => 'Galway',
    'gaza'          => 'Gaza',
    'ginza'         => 'Ginza', // Ginza line
    'gotham'        => 'Gotham',
    'gower'         => 'Gower', // peninsula
    'grande'        => 'Grande', // Rio Grande
    'graceland'     => 'Graceland', // like Disneyland, not really a place?
    'greeks'        => 'Greeks',
    'greenpoint'    => 'Greenpoint',
    'guernica'      => 'Guernica',
    'hampstead'     => 'Hampstead',
    'harlem'        => 'Harlem',
    'hepperties'    => 'Hepperties',
    'hindu'         => 'Hindu',
    'hollywood'     => 'Hollywood',
    "hollywood's"   => "Hollywood's",
    'hong'          => 'Hong', // Hong Kong
    'hudson'        => 'Hudson',
    'inisfree'      => 'Inisfree', // island
    'irisy'         => 'Irisy',
    'itchycoo'      => 'Itchycoo',
    "jack's"        => "Jack's", // Big Jack's, a club
    "jordan's"      => "Jordan's",
    'ken'           => 'Ken', // isles of Ken
    'kent'          => 'Kent',
    'kettering'     => 'Kettering',  // Sloan Kettering
    'khe'           => 'Khe', // Khe Sanh
    'khyber'        => 'Khyber',
    'kilda'         => 'Kilda', // St Kilda
    'kilimanjaro'   => 'Kilimanjaro',
    'kintyre'       => 'Kintyre',
    'kong'          => 'Kong', // Hong Kong
    'kowloon'       => 'Kowloon',
    'kremlin'       => 'Kremlin',
    "kremlin's"     => "Kremlin's",
    'kush'          => 'Kush', // Hindu Kush, mountain range
    'lahaina'       => 'Lahaina',
    'largo'         => 'Largo', // Key Largo
    'leeds'         => 'Leeds',
    'leith'         => 'Leith',
    'lido'          => 'Lido',
    'lieth'         => 'Lieth',
    'lincoln'       => 'Lincoln', // Lincoln High School, also a brand and a name
    'lords'         => 'Lords',
    'louvre'        => 'Louvre',
    'macquarie'     => 'Macquarie',
    'malvinas'      => 'Malvinas',
    'mahal'         => 'Mahal', // Taj Mahal
    'mandalay'      => 'Mandalay', // Mandalay Bay Hotel
    'manhattan'     => 'Manhattan',
    "manhattan's"   => "Manhattan's",
    'manly'         => 'Manly', // Manly ferry
    'margarita'     => 'Margarita', // Puerto Margarita
    'mariana'       => 'Mariana',
    'marrickville'  => 'Marrickville',
    'martinque'     => 'Martinque',
    'mersey'        => 'Mersey',
    'mississippi'   => 'Mississippi',
    "mississippi's" => "Mississippi's",
    'mojave'        => 'Mojave',
    'monserrat'     => 'Monserrat',
    'montego'       => 'Montego',
    'montelimar'    => 'Montelimar',
    'morningside'   => 'Morningside', // suburb of Edinburgh
    'mu'            => 'Mu', // Mu Mu land
    'neverland'     => 'Neverland',
    'ngall'         => 'Ngall',
    'niagara'       => 'Niagara',
    'nile'          => 'Nile',
    'northside'     => 'Northside',
    'olympia'       => 'Olympia',
    'olympus'       => 'Olympus',
    'pacific'       => 'Pacific',
    'panmunjong'    => 'Panmunjong',
    'parris'        => 'Parris',
    'piazza'        => 'Piazza', // Piazza Cavour
    'pluto'         => 'Pluto',
    'ponchatrain'   => 'Ponchatrain',
    'promity'       => 'Promity',
    'puerto'        => 'Puerto',
    'ramblas'       => 'Ramblas',
    'rio'           => 'Rio', // Rio Grande, a river, also a city
    'riviera'       => 'Riviera',
    'rockaway'      => 'Rockaway',
    'rockies'       => 'Rockies',
    'rotherhide'    => 'Rotherhide',
    'rouge'         => 'Rouge',
    'rubicon'       => 'Rubicon',
    'sacre'         => 'Sacre', // Sacre Coeur
    'sahara'        => 'Sahara',
    'saturn'        => 'Saturn',
    'savoy'         => 'Savoy',
    'scarborough'   => 'Scarborough',
    'serengeti'     => 'Serengeti',
    'shannon'       => 'Shannon',
    'shenandoah'    => 'Shenandoah',
    'siberia'       => 'Siberia',
    'sicily'        => 'Sicily',
    'sloan'         => 'Sloan',
    'smithfield'    => 'Smithfield',
    'soho'          => 'Soho',
    'sorbonne'      => 'Sorbonne',
    'st'            => 'St', // St Kilda St Tropez
    'staten'        => 'Staten',
    "stroh's"       => "Stroh's",
    'suez'          => 'Suez',
    'swathmore'     => 'Swathmore',
    'taj'           => 'Taj',
    'tempe'         => 'Tempe',
    'tetons'        => 'Tetons',
    'thames'        => 'Thames',
    'tirolean'      => 'Tirolean',
    'transylvania'  => 'Transylvania',
    'travelga'      => 'Travelga',
    'tropez'        => 'Tropez',
    'tyne'          => 'Tyne',
    'uranus'        => 'Uranus',
    'ventura'       => 'Ventura',
    'venetian'      => 'Venetian',
    'venus'         => 'Venus',
    'victoria'      => 'Victoria',
    'vieux'         => 'Vieux' , // Vieux Carre church
    'warwick'       => 'Warwick', // Warwick Hotel
    'westwood'      => 'Westwood', // part of East Kilbride
    'whitehouse'    => 'Whitehouse',
    'xanadu'        => 'Xanadu',
    'xenia'         => 'Xenia',

];

