<?php

return [

    /*
    |--------------------------------------------------------------------------
    | States
    |--------------------------------------------------------------------------
    |
    | States, provinces, state dimunitives, persons of a state.
    |
    */

    "a-lou'sian'"       => "a-Lou'sian'",
    "alabam'"           => "Alabam'",
    'alabama'           => 'Alabama',
    'alaska'            => 'Alaska',
    'alberta'           => 'Alberta',
    'arizona'           => 'Arizona',
    'arkansas'          => 'Arkansas',
    'bamee'             => 'Bamee',
    'cali'              => 'Cali',
    'california'        => 'California',
    "california's"      => "California's",
    'californication'   => 'Californication',
    'colorado'          => 'Colorado',
    'connecticut'       => 'Connecticut',
    'delaware'          => 'Delaware',
    'fla'               => 'FLA',
    'florida'           => 'Florida',
    "florida's"         => "Florida's",
    'g-a'               => 'G-A',
    'georgia'           => 'Georgia',
    'georgian'          => 'Georgian',
    'hawaii'            => 'Hawaii',
    'hawaiian'          => 'Hawaiian',
    'idaho'             => 'Idaho',
    'illinois'          => 'Illinois',
    'indiana'           => 'Indiana',
    "indiana's"         => "Indiana's",
    'iowa'              => 'Iowa',
    'jersey'            => 'Jersey',
    'kansas'            => 'Kansas',
    'kansas-born'       => 'Kansas-born',
    'kentucky'          => 'Kentucky',
    'louisiana'         => 'Louisiana',
    'maine'             => 'Maine',
    'maryland'          => 'Maryland',
    'massachusetts'     => 'Massachusetts',
    'massastu-sus'      => 'Massastu-sus',
    'michigan'          => 'Michigan',
    'minnesota'         => 'Minnesota',
    'mississippi'       => 'Mississippi',
    'missouri'          => 'Missouri',
    'montana'           => 'Montana',
    'nebraska'          => 'Nebraska',
    'nevada'            => 'Nevada',
    'new hampshire'     => 'New Hampshire',
    'new jersey'        => 'New Jersey',
    'new mexico'        => 'New Mexico',
    'new york'          => 'New York',
    'north carolina'    => 'North Carolina',
    'north dakota'      => 'North Dakota',
    'ohio'              => 'Ohio',
    'oklahoma'          => 'Oklahoma',
    'oregon'            => 'Oregon',
    'pa'                => 'PA',
    'pennsylvania'      => 'Pennsylvania',
    'rhode'             => 'Rhode',
    'rhode island'      => 'Rhode Island',
    'south carolina'    => 'South Carolina',
    'south dakota'      => 'South Dakota',
    'tennessee'         => 'Tennessee',
    'texas'             => 'Texas',
    'utah'              => 'Utah',
    'vermont'           => 'Vermont',
    'virginia'          => 'Virginia',
    'virginny'          => 'Virginny',
    'washington'        => 'Washington',
    'west virginia'     => 'West Virginia',
    'wisconsin'         => 'Wisconsin',
    'wyoming'           => 'Wyoming',

];
