<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Towns
    |--------------------------------------------------------------------------
    |
    | Towns, cities, villages, or part thereof
    |
    */

    "'frisco"           => "'Frisco",
    'aberdeen'          => 'Aberdeen',
    'aberdine'          => 'Aberdine',
    'acapulco'          => 'Acapulco',
    'accrington'        => 'Accrington',
    'agadir'            => 'Agadir',
    'aires'             => 'Aires', // Buenos Aires
    'albuquerque'       => 'Albuquerque',
    'algiers'           => 'Algiers',
    'allentown'         => 'Allentown',
    'amsterdam'         => 'Amsterdam',
    'anaheim'           => 'Anaheim',
    'anchorage'         => 'Anchorage',
    'angeles'           => 'Angeles',
    'athens'            => 'Athens',
    'atlanta'           => 'Atlanta',
    "atlanta's"         => "Atlanta's",
    'austin'            => 'Austin', // also a name
    'aviv'              => 'Aviv', // Tel Aviv
    'azul'              => 'Azul', // Cerro Azul
    'baghdad'           => 'Baghdad',
    'bally'             => 'Bally',
    'baltimore'         => 'Baltimore',
    'bangkok'           => 'Bangkok',
    'barcelona'         => 'Barcelona',
    'barstow'           => 'Barstow',
    'baton'             => 'Baton', // Baton Rouge
    'beaumont'          => 'Beaumont',
    'beijing'           => 'Beijing',
    'beirut'            => 'Beirut',
    'belfast'           => 'Belfast',
    'berlin'            => 'Berlin',
    'bethlehem'         => 'Bethlehem',
    'beverly'           => 'Beverly', // Beverly Hills, also a name
    'bien'              => 'Bien', // Dien Bien Phu
    'birmingham'        => 'Birmingham',
    'bissau'            => 'Bissau',
    'bombay'            => 'Bombay',
    'boston'            => 'Boston',
    'brighton'          => 'Brighton',
    "brisbane's"        => "Brisbane's",
    'brussels'          => 'Brussels',
    'buenos'            => 'Buenos', // Buenos Aires
    'calgary'           => 'Calgary',
    'cannes'            => 'Cannes',
    'carlisle'          => 'Carlisle',
    'carson'            => 'Carson', // also a name
    'cebu'              => 'Cebu',
    'cerro'             => 'Cerro', // Cerro Azul
    'chattanooga'       => 'Chattanooga',
    'chernobyl'         => 'Chernobyl',
    'chi-town'          => 'Chi-Town',
    'chicago'           => 'Chicago',
    'cleveland'         => 'Cleveland',
    'constantinople'    => 'Constantinople',
    'copmanhurst'       => 'Copmanhurst',
    'corning'           => 'Corning',
    'darwin'            => 'Darwin',
    'dearborn'          => 'Dearborn',
    'detroit'           => 'Detroit',
    'dharamsala'        => 'Dharamsala',
    'diego'             => 'Diego', // San Diego 
    'dien'              => 'Dien', // Dien Bien Phu
    'dublin'            => 'Dublin',
    'duluth'            => 'Duluth',
    'dunblane'          => 'Dunblane',
    'dundee'            => 'Dundee',
    'ebudae'            => 'Ebudae',
    'emmeline'          => 'Emmeline',
    'fe'                => 'Fe', // Santa Fe
    'finnoe'            => 'Finnoe',
    'francisco'         => 'Francisco', // San Francisco
    "francisco's"       => "francisco's",
    'frisco'            => 'Frisco', // San Francisco
    'frontenac'         => 'Frontenac',
    'fulsom'            => 'Fulsom',
    'gainesville'       => 'Gainesville',
    'galveston'         => 'Galveston',
    'geneva'            => 'Geneva',
    "geneva's"          => "Geneva's",
    'glenaveigh'        => 'Glenaveigh',
    'glendale'          => 'Glendale',
    'grasmeres'         => 'Grasmeres',
    'greenville'        => 'Greenville',
    'guantanamo'        => 'Guantanamo',
    'guernica'          => 'Guernica',
    'hackensack'        => 'Hackensack',
    'hiroshima'         => 'Hiroshima',
    'hobart'            => 'Hobart',
    'houston'           => 'Houston',
    'humberside'        => 'Humberside',
    'huntington'        => 'Huntington',
    'hyannisport'       => 'Hyannisport',
    'istanbul'          => 'Istanbul',
    'jackson'           => 'Jackson', // Also a name
    "jacksonville's"    => "Jacksonville's",
    'janeiro'           => 'Janeiro',
    'jerusalem'         => 'Jerusalem',
    'johannesburg'      => 'Johannesburg',
    'jose'              => 'Jose', // San Jose, also a name 
    'juarez'            => 'Juarez',
    'kalamazoo'         => 'Kalamazoo',
    'khartoum'          => 'Khartoum',
    'kilronan'          => 'Kilronan',
    'kingston'          => 'Kingston',
    'kingstown'         => 'Kingstown',
    'kokomo'            => 'Kokomo',
    'kowloon'           => 'Kowloon',
    'lafayette'         => 'Lafayette',
    'laguna'            => 'Laguna', // Laguan Beach
    'lansing'           => 'Lansing',
    'laramie'           => 'Laramie',
    'l.a.'              => 'L.A.',
    'l.a'               => 'L.A',
    'la'                => 'LA', // Los Angeles, this will be a problem
    'las'               => 'Las', // Las Vegas
    'leodiensian'       => 'Leodiensian',
    'lethbridge'        => 'Lethbridge',
    'liula'             => 'Liula',
    'liverpool'         => 'Liverpool',
    'london'            => 'London',
    'los'               => 'Los', // Los Angeles
    'madison'           => 'Madison',
    'malibu'            => 'Malibu',
    'melbourne'         => 'Melbourne',
    'memphis'           => 'Memphis',
    'metuchen'          => 'Metuchen',
    'miami'             => 'Miami', // Miami Beach
    'milan'             => 'Milan',
    'minneapolis'       => 'Minneapolis',
    'monica'            => 'Monica', // Santa Monica
    'monterey'          => 'Monterey', // Mexico
    'montgomery'        => 'Montgomery',
    'montreux'          => 'Montreux',
    'morningtown'       => 'Morningtown',
    'moscow'            => 'Moscow',
    'nacogdoches'       => 'Nacogdoches',
    'napoli'            => 'Napoli',
    'naples'            => 'Naples',
    'narrabri'          => 'Narrabri',
    'nashville'         => 'Nashville',
    'nassau'            => 'Nassau',
    'newark'            => 'Newark',
    'newcastle'         => 'Newcastle',
    'ngall'             => 'Ngall',
    'northcliff'        => 'Northcliff',
    'nutbush'           => 'Nutbush',
    'nyc'               => 'NYC',
    'oaktown'           => 'Oaktown',
    'olomouc'           => 'Olomouc',
    'opelousas'         => 'Opelousas',
    'orleans'           => 'Orleans', // New Orleans
    'oxford'            => 'Oxford',
    'paris'             => 'Paris',
    'parisian'          => 'Parisian',
    'paso'              => 'Paso', // El Paso
    'peking'            => 'Peking',
    'perth'             => 'Perth',
    'philadelphia'      => 'Philadelphia',
    'philly'            => 'Philly',
    'phoenix'           => 'Phoenix', // also a word
    'phu'               => 'Phu', // Dien Bien Phu
    'piha'              => 'Piha',
    'pineola'           => 'Pineola',
    'pisa'              => 'Pisa',
    'pittsburgh'        => 'Pittsburgh',
    'pomona'            => 'Pomona',
    'provincetown'      => 'Provincetown',
    'reno'              => 'Reno',
    'rimini'            => 'Rimini',
    'rincon'            => 'Rincon',
    'rio'               => 'Rio',
    'rockville'         => 'Rockville',
    'rollox'            => 'Rollox',
    'rome'              => 'Rome',
    'rosedale'          => 'Rosedale',
    'rouge'             => 'Rouge', // Baton
    'saginaw'           => 'Saginaw',
    'sanh'              => 'Sanh', // Khe Sanh
    'san'               => 'San',
    'savannah'          => 'Savannah',
    'segundo'           => 'Segundo', // El Segundo
    'shinrone'          => 'Shinrone',
    'slidell'           => 'Slidell',
    'smithfield'        => 'Smithfield',
    'sorrento'          => 'Sorrento',
    'spokane'           => 'Spokane',
    'stanley'           => 'Stanley', // also a name
    'subiaco'           => 'Subiaco',
    'sydney'            => 'Sydney',
    "sydney's"          => "Sydney's",
    'tacoma'            => 'Tacoma',
    'taipei'            => 'Taipei',
    'tampa'             => 'Tampa',
    'taroudant'         => 'Taroudant',
    'tel'               => 'Tel', // Tel Aviv
    'tipperary'         => 'Tipperary',
    'tiree'             => 'Tiree',
    'tokyo'             => 'Tokyo',
    'toronto'           => 'Toronto',
    'trenton'           => 'Trenton',
    'troy'              => 'Troy',
    'tucson'            => 'Tucson',
    'tulsa'             => 'Tulsa',
    'turin'             => 'Turin',
    'utrecht'           => 'Utrecht',
    "vancouver's"       => "Vancouver's",
    'vegas'             => 'Vegas', // Las Vegas
    'venetian'          => 'Venetian',
    'venice'            => 'Venice',
    'ventura'           => 'Ventura',
    'vienna'            => 'Vienna',
    'walla'             => 'Walla',
    'waterloo'          => 'Waterloo', // village in France
    'watertown'         => 'Watertown',
    'wellfleet'         => 'Wellfleet',
    'wellington'        => 'Wellington',
    'winnemucca'        => 'Winnemucca',
    'york'              => 'York',

];
