<?php

return [

    'Aberdeen',
    'Aberdine',
    'Acapulco',
    'Accrington',
    'Aires', // Buenos Aires
    'Albuquerque',
    'Algiers',
    'Allentown',
    'Amsterdam',
    'Anaheim',
    'Angeles',
    'Athens',
    'Atlanta',
    'Austin', // also a name
    'Aviv', // Tel Aviv
    'Azul', // Cerro Azul
    'Baghdad',
    'Bally',
    'Baltimore',
    'Bangkok',
    'Barcelona',
    'Barrington',
    'Barstow',
    'Baton', // Baton Rouge
    'Beaumont',
    'Beijing',
    'Beirut',
    'Belfast',
    'Belmont',
    'Bergere',
    'Berlin',
    'Bethlehem',
    'Beverly', // also a name
    'Bien', // Dien Bien Phu
    'Birmingham',
    'Bissau',
    'Bombay',
    'Boston',
    'Brighton',
    'Brussels',
    'Buenos', // Buenos Aires
    'Calgary',
    'Campbell', // also a name
    'Canaan',
    'Cannes',
    'Carlisle',
    'Carson', // also a name
    'Cauldrum',
    'Cebu',
    'Cerro',
    'Chattanooga',
    'Chernobyl',
    'Chicago',
    'Chicano',
    'Cicero', // also a name
    'Cienega',
    'Cleveland',
    'Constantinople',
    'Copmanhurst',
    'Corning',
    'Costa',
    'Cronkite',
    'Danforth',
    'Detroit',
    'Dharamsala',
    'Diego', // San Diego 
    'Dien', // Dien Bien Phu
    'Dublin',
    'Dunblane',
    'Dundee',
    'Ebudae',
    'Eden',
    'Finnoe',
    'Francisco', // San Francisco
    'Frisco', // San Francisco
    'Frontenac',
    'Fulsom',
    'Galveston',
    'Geneva',
    'Ginza',
    'Glenaveigh',
    'Gower',
    'Grasmeres',
    'Greenville',
    'Guantanamo',
    'Guernica',
    'Hindu', // Hindu Stan?
    'Hobart',
    'Humberside',
    'Huntington',
    'Hyannisport',
    'Inisfree',
    'Istanbul',
    'Jackson', // Also a name 
    'Jose', // San Jose, also a name 
    'Khartoum',
    'Kilronan',
    'Kokomo',
    'Kowloon',
    'Kush',
    'Laguna', // Laguan Beach
    'Las', // Las Vegas
    'Lethbridge',
    'Liula',
    'Liverpool',
    'Los', // Los Angeles
    'Madison',
    'Malibu',
    'Melbourne',
    'Memphis',
    'Metuchen',
    'Monica', // Santa Monica
    'Montague',
    'Montgomery',
    'Montreux',
    'Morningside',
    'Moscow',
    'Napoli',
    'Narrabri',
    'Ngall',
    'Oaktown',
    'Olomouc',
    'Opelousas',
    'Orleans', // New Orleans
    'Oxford',
    'Perth',
    'Peyton',
    'Philly',
    'Phu', // Dien Bien Phu
    'Piha',
    'Pineola',
    'Pomona',
    'Provincetown',
    'Reno',
    'Rimini',
    'Rincon',
    'Rockville',
    'Rollox',
    'Rosedale',
    'Rotherhide',
    'Rouge',
    'Sanh', // Khe Sanh
    'Scarborough',
    'Shinrone',
    'Slidell',
    'Smithfield',
    'Sorrento',
    'Subiaco',
    'Sydney',
    'Taroudant',
    'Tel', // Tel Aviv
    'Tipperary',
    'Tiree',
    'Trenton',
    'Tucson',
    'Vegas', // Las Vegas
    'Ventura',
    'Walla',
    'Watertown',
    'Westwood',
    'Winnemucca',
    'Xenia',
    'Zelda',
];
